stages:
  - build
  - release
  - deploy

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  tags:
    - api-build
  only:
    - master
  script:
    - docker build . -t acm-registry:5000/api:$CI_PIPELINE_ID

release:
  stage: release
  tags:
    - api-release
  only:
    - master
  script:
    - docker tag acm-registry:5000/api:$CI_PIPELINE_ID acm-registry:5000/api:production-latest
    - docker push acm-registry:5000/api:production-latest

deploy:
  stage: deploy
  tags:
    - api-deploy
  only:
    - master
  script:
    - docker service update --image acm-registry:5000/api:production-latest api_api

