version: "3.7"

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - RUNNING_HOST=127.0.0.1
      - DEBUG_MODE=True
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - SECRET_KEY=
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
    volumes:
      - ./static:/app/static
      - ./images:/app/images

  webserver:
    image: nginx:1.17.1
    ports:
      - 80:80
    volumes:
      - ./.nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static
      - ./images:/var/www/images
  database:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
