version: "3.7"

networks: 
  app-tier:
    driver: bridge

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - RUNNING_HOST=127.0.0.1
      - DEBUG_MODE=True
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=***REMOVED***
      - SECRET_KEY=***REMOVED***
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - RABBIT_HOST = rabbit
    volumes:
      - ./static:/app/static
      - ./images:/app/images
    networks: 
      - app-tier

  webserver:
    image: nginx:1.17.1
    ports:
      - 80:80
    volumes:
      - ./.nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static
      - ./images:/var/www/images
  database:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=***REMOVED***
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:management
    ports: 
      # - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks: 
      - app-tier

volumes:
  pgdata:
