# Generated by Django 2.2.3 on 2019-08-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_contest_contestimage_maincontest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestimage',
            name='contest',
        ),
        migrations.DeleteModel(
            name='MainContest',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='ContestImage',
        ),
    ]
