# Generated by Django 2.2.3 on 2019-09-19 15:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20190828_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='innerHTML',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
