# Generated by Django 2.2.3 on 2019-09-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20190919_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='innerHTML',
            field=models.TextField(),
        ),
    ]
