# Generated by Django 2.2.3 on 2019-09-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnsiteTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usermanagement.Team')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('RESERVED', 'Reserved registration beforehand'), ('PENDING', 'Pending'), ('APPROVED', 'Approved for participation'), ('REJECTED', 'Denied Participation')], default='PENDING', max_length=50)),
            ],
            bases=('usermanagement.team',),
        ),
        migrations.RemoveField(
            model_name='team',
            name='country',
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_onsite',
        ),
        migrations.RemoveField(
            model_name='team',
            name='status',
        ),
        migrations.CreateModel(
            name='OnlineTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usermanagement.Team')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved for participation'), ('REJECTED', 'Denied Participation')], default='PENDING', max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Country')),
            ],
            bases=('usermanagement.team',),
        ),
    ]
