# Generated by Django 2.2.5 on 2019-10-06 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='online_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='online_subject',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='onlineteam',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='email',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Email must be entered correctly.')]),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered correctly.', regex='^(\\+98|0)?9\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='onlineteam',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved for payment'), ('REJECTED', 'Denied Participation')], default='APPROVED', max_length=50),
        ),
        migrations.AlterField(
            model_name='onsiteteam',
            name='status',
            field=models.CharField(choices=[('PAID', 'Finalized Registration'), ('RESERVED', 'Reserved registration beforehand'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved for payment'), ('REJECTED', 'Denied Participation')], default='PENDING', max_length=50),
        ),
    ]
