# Generated by Django 2.2.4 on 2019-09-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20190831_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
