# Generated by Django 2.2.5 on 2019-10-10 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20191006_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='email',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Email must be entered correctly.')]),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='student_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='onlineteam',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved for payment'), ('REJECTED', 'Denied Participation')], default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='institution',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
