# Generated by Django 2.2.3 on 2019-10-24 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_auto_20191011_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered correctly.', regex='^(\\+98|0)?9\\d{9}$')]),
        ),
    ]
