# Generated by Django 2.2.3 on 2019-09-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_onlineteam_onsiteteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='usermanagement.Team'),
        ),
    ]
