# Generated by Django 2.2.5 on 2020-10-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_auto_20191024_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailmessage',
            old_name='paid_content',
            new_name='finalized_content',
        ),
        migrations.RenameField(
            model_name='mailmessage',
            old_name='denied_content',
            new_name='rejected_content',
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='denied_subject',
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='paid_subject',
        ),
        migrations.RemoveField(
            model_name='onlineteam',
            name='password',
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='finalized_subject',
            field=models.TextField(default='Finalized'),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='rejected_subject',
            field=models.TextField(default='Rejected'),
        ),
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='online_subject',
            field=models.TextField(default='Online Contest Registration'),
        ),
        migrations.AlterField(
            model_name='onlineteam',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('REJECTED', 'Denied Participation'), ('FINALIZED', 'Finalized Registration')], default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='onsiteteam',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved for payment'), ('RESERVED', 'Reserved registration beforehand'), ('PENDING', 'Pending Approval'), ('REJECTED', 'Denied Participation'), ('FINALIZED', 'Finalized Registration')], default='PENDING', max_length=50),
        ),
    ]
