# Generated by Django 2.2.10 on 2020-10-31 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_auto_20201021_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='student_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\d{1, 20}$')]),
        ),
        migrations.AlterField(
            model_name='onlineteam',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('REJECTED', 'Denied Participation'), ('FINALIZED', 'Finalized Registration')], default='PENDING', max_length=20),
        ),
    ]
