# Generated by Django 2.2.10 on 2020-10-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_auto_20201031_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsiteteam',
            name='is_high',
            field=models.BooleanField(default=False),
        ),
    ]
