# Generated by Django 2.2.10 on 2020-11-01 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0008_onsiteteam_is_high'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='student_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='\\d{1,20}')]),
        ),
    ]
