# Generated by Django 2.2.27 on 2023-01-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_auto_20201101_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsiteteam',
            name='is_high',
            field=models.BooleanField(default=False, help_text='Is it a team from high-schools?'),
        ),
    ]
