version: "3.7"

services:
  api:
    image: acm-registry:5000/api:production-latest
    ports:
      - 8000:8000
    env_file:
      - /etc/apps.env/api.env
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /app/static
        target: /var/www/static
    networks:
      - production-net

networks:
  production-net:
    external: true
