# Generated by Django 2.2.4 on 2019-09-01 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=500)),
                ('thumbnail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ACM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('problems', models.CharField(max_length=500)),
                ('final_ranking_onsite', models.CharField(max_length=500)),
                ('final_ranking_online', models.CharField(max_length=550)),
                ('poster', models.CharField(blank=True, max_length=500, null=True)),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Image')),
            ],
            options={
                'verbose_name': 'CONTEST',
                'verbose_name_plural': 'CONTESTS',
            },
        ),
    ]
