# Generated by Django 2.2.5 on 2019-10-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='has_passed',
            field=models.BooleanField(default=True),
        ),
    ]
