# Generated by Django 2.2.3 on 2019-09-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0001_initial'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.TextField(verbose_name='thumbnail_url')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contest_photo', to='photologue.Photo')),
                ('thumbnail_size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contest_photo', to='photologue.PhotoSize')),
            ],
            options={
                'verbose_name': 'Contest Photo',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='photologue.Gallery')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='contests.Contest')),
            ],
            options={
                'verbose_name': 'Contest Gallery',
                'verbose_name_plural': 'Contest Galleries',
            },
            bases=('photologue.gallery',),
        ),
    ]
