# Generated by Django 2.2.4 on 2019-08-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acm',
            options={'verbose_name': 'ACM', 'verbose_name_plural': 'ACM CONTEST'},
        ),
    ]
