# Generated by Django 2.2.3 on 2019-09-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='poster',
            field=models.ImageField(default=None, upload_to='', verbose_name='poster'),
            preserve_default=False,
        ),
    ]
