# Generated by Django 2.2.5 on 2020-10-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contest_has_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcontest',
            name='online_team_starting_user_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='currentcontest',
            name='onsite_team_starting_user_count',
            field=models.IntegerField(default=0),
        ),
    ]
