# Generated by Django 2.2.3 on 2019-09-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contest_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='src',
        ),
    ]
