# Generated by Django 2.2.4 on 2019-09-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_remove_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acm',
            name='images',
        ),
        migrations.AddField(
            model_name='acm',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='contests.Image'),
        ),
    ]
