# Generated by Django 2.2.3 on 2019-09-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_gallery_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contest_photo', to='photologue.PhotoSize'),
        ),
    ]
