# Generated by Django 2.2.3 on 2019-09-02 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gallery_ptr',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
