# Generated by Django 2.2.3 on 2019-09-02 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('contests', '0004_auto_20190902_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('problems', models.CharField(max_length=500)),
                ('final_ranking_onsite', models.CharField(max_length=500)),
                ('final_ranking_online', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='photologue.Gallery')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
            ],
            options={
                'verbose_name': 'Contest Gallery',
                'verbose_name_plural': 'Contest Galleries',
            },
            bases=('photologue.gallery',),
        ),
    ]
