# Generated by Django 2.2.4 on 2019-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20190829_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acm',
            name='judge_solution',
        ),
        migrations.RemoveField(
            model_name='acm',
            name='test_data',
        ),
        migrations.AlterField(
            model_name='acm',
            name='final_ranking_onsite',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='acm',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
