# Generated by Django 2.2.3 on 2019-09-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Contest Photo'},
        ),
    ]
