# Generated by Django 2.2.3 on 2019-09-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20190903_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='title',
        ),
        migrations.AddField(
            model_name='contest',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='contest',
            name='final_ranking_online',
            field=models.CharField(max_length=500),
        ),
    ]
